use anyhow::{bail, Result};

use crate::config::Config;

const TEMPLATE: &str = r#"# LATTICE Agent Profile
# Generated by `lattice new agent`

[agent]
name = "AGENT_NAME"
model = "{MODEL}"
skippable = false
tags = []

[system]
prompt = "You are a helpful assistant. Return JSON."

[tools]
enabled = ["read_file", "grep"]

[behavior]
behavior_type = "strict"
confidence_threshold = 0.7
max_retries = 2

[handoff]
# fallback = "next-agent"

# Define handoff rules — evaluated in order, first match wins.
# [[handoff.rules]]
# condition = { field = "confidence", op = ">", value = "0.5" }
# target = "next-agent"
#
# [[handoff.rules]]
# default = true
# target = null  # pipeline ends
"#;

pub fn run(name: String) -> Result<()> {
    let agents_dir = super::safe_agents_dir(None).map_err(anyhow::Error::msg)?;
    let dir = agents_dir.join(&name);

    if dir.exists() {
        bail!("Agent '{}' already exists at '{}'", name, dir.display());
    }

    std::fs::create_dir_all(&dir)?;

    // Load config to get default model
    let config = Config::load(None)?;
    let default_model = config.default_model();

    let template = TEMPLATE
        .replace("AGENT_NAME", &name)
        .replace("{MODEL}", &default_model);
    let toml_path = dir.join("agent.toml");
    std::fs::write(&toml_path, template)?;

    println!("Created agent '{}' at {}", name, dir.display());
    println!();
    println!("  {}", toml_path.display());
    println!();
    println!("Edit the file to configure your agent, then run:");
    println!("  lattice validate {}", agents_dir.display());
    println!();

    Ok(())
}
